version: '3.8'

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo:7.0.4
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - nextjs
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok"
        ]
      interval: 2s
      timeout: 20s
      retries: 10
      start_period: 20s
      start_interval: 2s
  mymoney:
    container_name: mymoney
    build:
      context: ./mymoney
      dockerfile: dev.Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./mymoney/app:/mymoney/app/
      - ./mymoney/public:/mymoney/public
      - ./mymoney/lib:/mymoney/lib/
    restart: always
    ports:
      - 80:3000
    networks:
      - nextjs
    # command: sh migrate-and-start-dev.sh
    depends_on:
      mongo:
        condition: service_healthy

networks:
  nextjs:


volumes:
  mongodb-data:
    driver: local
