version: '3.8'

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nextjs
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 20s
      retries: 10
      start_period: 20s
      start_interval: 2s
  mymoney:
    container_name: mymoney
    build:
      context: .
      dockerfile: prod.Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app/
      - ./public:/app/public
      - ./.next:/app/.next
      - ./prisma:/app/prisma
    restart: always
    ports:
      - 80:3000
    networks:
      - nextjs
    depends_on:
      - postgres

networks:
  nextjs:

volumes:
  postgres-data:
    driver: local
